# Generated by Django 4.0 on 2021-12-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csvModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dteday', models.DateField(auto_now=True)),
                ('season', models.IntegerField()),
                ('yr', models.IntegerField()),
                ('mnth', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('holiday', models.IntegerField()),
                ('weekday', models.IntegerField()),
                ('workingday', models.IntegerField()),
                ('weathersit', models.IntegerField()),
                ('temp', models.FloatField()),
                ('atemp', models.FloatField()),
                ('hum', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('casual', models.IntegerField()),
                ('registered', models.IntegerField()),
                ('cnt', models.IntegerField()),
            ],
        ),
    ]
