# Generated by Django 4.0 on 2021-12-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='csvModel',
        ),
    ]
